// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/layouts/default-layout/index.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    TabLayout: typeof import('./src/components/layouts/tab-layout/index.vue')['default']
    TestSlot: typeof import('./src/components/test-slot.vue')['default']
  }
}
