// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/default-layout/index.vue')['default']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
  }
}
